// <auto-generated />
using System;
using System.Collections.Generic;
using Aderfia.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aderfia.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(AderfiaDbContext))]
    [Migration("20260918010148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aderfia.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Aderfia.Domain.Catalog.Category.Description#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MetaDescription", "Aderfia.Domain.Catalog.Category.MetaDescription#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("MetaDescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("MetaDescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MetaTitle", "Aderfia.Domain.Catalog.Category.MetaTitle#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MetaTitleAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MetaTitleEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Aderfia.Domain.Catalog.Category.Name#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("NameEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tagline", "Aderfia.Domain.Catalog.Category.Tagline#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)")
                                .HasColumnName("TaglineAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)")
                                .HasColumnName("TaglineEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Position");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("HeroImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Aderfia.Domain.Catalog.Collection.Description#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MetaDescription", "Aderfia.Domain.Catalog.Collection.MetaDescription#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("MetaDescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("MetaDescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MetaTitle", "Aderfia.Domain.Catalog.Collection.MetaTitle#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MetaTitleAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MetaTitleEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Subtitle", "Aderfia.Domain.Catalog.Collection.Subtitle#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)")
                                .HasColumnName("SubtitleAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)")
                                .HasColumnName("SubtitleEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "Aderfia.Domain.Catalog.Collection.Title#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("TitleAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("TitleEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HeroImageId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DefaultVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("RatingAverage")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("CareInstructions", "Aderfia.Domain.Catalog.Product.CareInstructions#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("CareAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("CareEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Aderfia.Domain.Catalog.Product.Description#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("DescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("DescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MetaDescription", "Aderfia.Domain.Catalog.Product.MetaDescription#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("MetaDescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("MetaDescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("MetaTitle", "Aderfia.Domain.Catalog.Product.MetaTitle#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MetaTitleAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("MetaTitleEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Aderfia.Domain.Catalog.Product.Name#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("NameEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Story", "Aderfia.Domain.Catalog.Product.Story#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("StoryAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("StoryEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Tagline", "Aderfia.Domain.Catalog.Product.Tagline#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)")
                                .HasColumnName("TaglineAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(240)
                                .HasColumnType("nvarchar(240)")
                                .HasColumnName("TaglineEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DefaultVariantId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsPublished", "CategoryId", "IsFeatured");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tone")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Label", "Aderfia.Domain.Catalog.ProductBadge.Label#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("LabelAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("LabelEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductBadges", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlurDataUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("AltText", "Aderfia.Domain.Catalog.ProductImage.AltText#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("AltTextAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("AltTextEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ProductId", "Role", "Position");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Aderfia.Domain.Catalog.ProductMaterial.Name#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("NameEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Position");

                    b.HasIndex("ProductId", "Position")
                        .IsUnique();

                    b.ToTable("ProductMaterials", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Aderfia.Domain.Catalog.ProductOption.Name#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("NameEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOptions", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Swatch")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Aderfia.Domain.Catalog.ProductOptionValue.Value#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("ValueAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("ValueEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.ToTable("ProductOptionValues", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RelatedProductId");

                    b.HasIndex("ProductId", "RelatedProductId")
                        .IsUnique();

                    b.ToTable("ProductRelations", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Group", "Aderfia.Domain.Catalog.ProductSpecification.Group#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("GroupAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("GroupEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Label", "Aderfia.Domain.Catalog.ProductSpecification.Label#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("LabelAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("LabelEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Value", "Aderfia.Domain.Catalog.ProductSpecification.Value#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(600)
                                .HasColumnType("nvarchar(600)")
                                .HasColumnName("ValueAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(600)
                                .HasColumnType("nvarchar(600)")
                                .HasColumnName("ValueEn");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Position");

                    b.ToTable("ProductSpecifications", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CompareAtAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Aderfia.Domain.Catalog.ProductVariant.Name#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("NameEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Price", "Aderfia.Domain.Catalog.ProductVariant.Price#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.VariantOptionValue", b =>
                {
                    b.Property<Guid>("VariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OptionValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VariantId", "OptionValueId");

                    b.HasIndex("OptionValueId");

                    b.ToTable("VariantOptionValues", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefaultBilling")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultShipping")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Region")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnonymousId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("UnitPrice", "Aderfia.Domain.Customers.CartItem.UnitPrice#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptsMarketing")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Ordering.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ShippingMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShippingMethodName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("DiscountTotal", "Aderfia.Domain.Ordering.Order.DiscountTotal#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("DiscountTotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DiscountTotalCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("GrandTotal", "Aderfia.Domain.Ordering.Order.GrandTotal#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("GrandTotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("GrandTotalCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ShippingTotal", "Aderfia.Domain.Ordering.Order.ShippingTotal#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("ShippingTotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("ShippingTotalCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Subtotal", "Aderfia.Domain.Ordering.Order.Subtotal#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("SubtotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("SubtotalCurrency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TaxTotal", "Aderfia.Domain.Ordering.Order.TaxTotal#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("TaxTotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TaxTotalCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ShippingMethodId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "PlacedAt");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Ordering.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ComplexProperty<Dictionary<string, object>>("UnitPrice", "Aderfia.Domain.Ordering.OrderItem.UnitPrice#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Ordering.ShippingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("FreeAboveSubtotal")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "Aderfia.Domain.Ordering.ShippingMethod.Description#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("DescriptionAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)")
                                .HasColumnName("DescriptionEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Estimate", "Aderfia.Domain.Ordering.ShippingMethod.Estimate#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("EstimateAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("EstimateEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Aderfia.Domain.Ordering.ShippingMethod.Name#LocalizedText", b1 =>
                        {
                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("NameAr");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("NameEn");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Price", "Aderfia.Domain.Ordering.ShippingMethod.Price#Money", b1 =>
                        {
                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");
                        });

                    b.HasKey("Id");

                    b.ToTable("ShippingMethods", (string)null);
                });

            modelBuilder.Entity("CollectionProduct", b =>
                {
                    b.Property<Guid>("CollectionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CollectionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CollectionProducts", (string)null);
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Category", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.ProductImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aderfia.Domain.Catalog.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Image");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Collection", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.ProductImage", "HeroImage")
                        .WithMany()
                        .HasForeignKey("HeroImageId");

                    b.Navigation("HeroImage");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Catalog.ProductVariant", "DefaultVariant")
                        .WithMany()
                        .HasForeignKey("DefaultVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Aderfia.Domain.Common.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Depth")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<decimal?>("Diameter")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<decimal?>("FrameWidth")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<decimal?>("Height")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(9, 3)
                                .HasColumnType("decimal(9,3)");

                            b1.Property<decimal?>("Width")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Category");

                    b.Navigation("DefaultVariant");

                    b.Navigation("Dimensions")
                        .IsRequired();
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductBadge", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("Badges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Collection", null)
                        .WithMany("Images")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductMaterial", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("Materials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductOption", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("Options")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.ProductOption", "Option")
                        .WithMany("Values")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductRelation", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("RelatedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Catalog.Product", "RelatedProduct")
                        .WithMany()
                        .HasForeignKey("RelatedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RelatedProduct");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductSpecification", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aderfia.Domain.Catalog.Inventory", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AllowBackorder")
                                .HasColumnType("bit")
                                .HasColumnName("AllowBackorder");

                            b1.Property<bool>("IsMadeToOrder")
                                .HasColumnType("bit")
                                .HasColumnName("IsMadeToOrder");

                            b1.Property<string>("LeadTimeAr")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("LeadTimeAr");

                            b1.Property<string>("LeadTimeEn")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("LeadTimeEn");

                            b1.Property<int>("LowStockThreshold")
                                .HasColumnType("int")
                                .HasColumnName("LowStockThreshold");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("StockQuantity");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("ProductVariants");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.OwnsOne("Aderfia.Domain.Common.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Depth")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<decimal?>("Diameter")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<decimal?>("FrameWidth")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<decimal?>("Height")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(9, 3)
                                .HasColumnType("decimal(9,3)");

                            b1.Property<decimal?>("Width")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("ProductVariants");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId");
                        });

                    b.Navigation("Dimensions");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.VariantOptionValue", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.ProductOptionValue", "OptionValue")
                        .WithMany("Variants")
                        .HasForeignKey("OptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Catalog.ProductVariant", "Variant")
                        .WithMany("OptionValues")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionValue");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.Address", b =>
                {
                    b.HasOne("Aderfia.Domain.Customers.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.Cart", b =>
                {
                    b.HasOne("Aderfia.Domain.Customers.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.CartItem", b =>
                {
                    b.HasOne("Aderfia.Domain.Customers.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Catalog.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.WishlistItem", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Customers.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aderfia.Domain.Ordering.Order", b =>
                {
                    b.HasOne("Aderfia.Domain.Ordering.ShippingMethod", "ShippingMethod")
                        .WithMany()
                        .HasForeignKey("ShippingMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aderfia.Domain.Customers.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Aderfia.Domain.Ordering.OrderAddress", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("BillingCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("BillingCountry");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BillingFirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BillingLastName");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BillingLine1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("BillingLine2");

                            b1.Property<string>("Phone")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("BillingPhone");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)")
                                .HasColumnName("BillingPostalCode");

                            b1.Property<string>("Region")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("BillingRegion");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Aderfia.Domain.Ordering.OrderAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("ShippingCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("ShippingCountry");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingFirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ShippingLastName");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ShippingLine1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ShippingLine2");

                            b1.Property<string>("Phone")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("ShippingPhone");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("nvarchar(24)")
                                .HasColumnName("ShippingPostalCode");

                            b1.Property<string>("Region")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("ShippingRegion");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("ShippingAddress")
                        .IsRequired();

                    b.Navigation("ShippingMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aderfia.Domain.Ordering.OrderItem", b =>
                {
                    b.HasOne("Aderfia.Domain.Ordering.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Aderfia.Domain.Catalog.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("CollectionProduct", b =>
                {
                    b.HasOne("Aderfia.Domain.Catalog.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aderfia.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Collection", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Images");

                    b.Navigation("Materials");

                    b.Navigation("Options");

                    b.Navigation("RelatedProducts");

                    b.Navigation("Specifications");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductOption", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Aderfia.Domain.Catalog.ProductVariant", b =>
                {
                    b.Navigation("OptionValues");
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Aderfia.Domain.Customers.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Aderfia.Domain.Ordering.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
